my_string=input('Количество символов текста'.__len__())
print(len(my_string))
my_string=input('Количество символов текста'.upper())
print(my_string)
my_string=input('Количество символов текста'.lower())
print(my_string)
my_string=input('Количество символов текста'.replace(' ',''))
print(my_string)
my_string=input('Количество символов текста'[0])
print(my_string)
my_string=input('Количество символов текста'[-1])
print(my_string)
